name: Publish Release APK
on: workflow_dispatch

jobs:
          
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout main branch to calculate changelog
        uses: actions/checkout@v2
        
      - name: Upload APK to Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "app.json"
          overwrite: true
          update_latest_release: true
