name: Publish Release APK
on: workflow_dispatch

jobs:
          
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout main branch to calculate changelog
        uses: actions/checkout@v2
        
      - name: Calculate version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: Get updated commit SHA
        run: |
          echo "##[set-output name=commit_id;]$(git rev-parse HEAD)"
        id: updated_sha
        
      - name: Upload APK to Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "app.json"
          overwrite: true
          tag_name: v1.0.30
          draft: false
