name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:       
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
         java-version: 11
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Make Gradle executable
        run: cd android && chmod +x ./gradlew 
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease
      - name: Create release and upload apk
        uses: kyze8439690/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: android/app
